# Generated by Django 5.1 on 2024-10-13 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0002_product_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('selector', models.CharField(max_length=200)),
                ('tag_type', models.CharField(choices=[('OTHER', 'OTHER'), ('META', 'META')], default='OTHER', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='selector',
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrapper.vendor'),
        ),
    ]
