# Generated by Django 5.1 on 2024-10-13 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0003_vendor_remove_product_selector_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(max_length=300),
        ),
    ]
